"""add_task_system

Revision ID: 91dd2d9dc14f
Revises: 6788f870aec2
Create Date: 2026-01-01 14:06:12.532557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '91dd2d9dc14f'
down_revision: Union[str, Sequence[str], None] = '6788f870aec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_user_relations',
    sa.Column('relation_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('is_assigned', sa.Boolean(), nullable=True, comment='True: 担当者, False: 担当者でない'),
    sa.Column('reaction', sa.String(length=20), nullable=True, comment='join: 参加, absent: 不参加, undecided: 未定, no-reaction: 無反応'),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('relation_id'),
    sa.UniqueConstraint('task_id', 'user_id', name='unique_task_user_membership')
    )
    op.create_index(op.f('ix_task_user_relations_relation_id'), 'task_user_relations', ['relation_id'], unique=False)
    op.drop_index(op.f('ix_calendars_calendar_id'), table_name='calendars')
    op.drop_table('calendars')
    op.add_column('tasks', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('tasks', sa.Column('is_task', sa.Boolean(), nullable=False))
    op.alter_column('tasks', 'description',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('tasks', 'status',
               existing_type=mysql.VARCHAR(length=255),
               comment='未着手、進行中、完了、None=タスクではない',
               existing_nullable=True)
    op.create_index(op.f('ix_tasks_group_id'), 'tasks', ['group_id'], unique=False)
    op.drop_constraint(op.f('tasks_ibfk_1'), 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'place')
    op.drop_column('tasks', 'assigned_to')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('assigned_to', mysql.VARCHAR(length=36), nullable=True))
    op.add_column('tasks', sa.Column('place', mysql.VARCHAR(length=255), nullable=True))
    op.create_foreign_key(op.f('tasks_ibfk_1'), 'tasks', 'users', ['assigned_to'], ['user_id'])
    op.drop_index(op.f('ix_tasks_group_id'), table_name='tasks')
    op.alter_column('tasks', 'status',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='未着手、進行中、完了、None=タスクではない',
               existing_nullable=True)
    op.alter_column('tasks', 'description',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('tasks', 'is_task')
    op.drop_column('tasks', 'location')
    op.create_table('calendars',
    sa.Column('calendar_id', mysql.VARCHAR(length=36), nullable=False),
    sa.PrimaryKeyConstraint('calendar_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_calendars_calendar_id'), 'calendars', ['calendar_id'], unique=False)
    op.drop_index(op.f('ix_task_user_relations_relation_id'), table_name='task_user_relations')
    op.drop_table('task_user_relations')
    # ### end Alembic commands ###